;track ids
.ENUM
	track_gravityman
	track_stoneman
	track_waveman
	track_starman
	track_crystalman
	track_gyroman
	track_chargeman
	track_napalmman
	track_darkman
	track_wily
	track_boss_fighting
	track_opening
	track_ending
	track_stage_select
	track_boss_show
	track_darkman_castle
	track_wily_castle
	track_boss_defeated
	track_game_over
	track_password
	track_get_weapon
	track_wily_defeated
	track_wily_fighting
	track_lighting
	track_route
	track_wily_ufo
	track_mega_buster
	track_landing
	track_megaman_hit
	track_death
	track_enemy_immune
	track_pipe
	track_half_charge_shot
	track_full_charge_shot
	track_charge_shot_full_charging
	track_charge_kick
	track_1up
	track_door
	track_refill
	track_select
	track_confirm
	track_open_menu
	track_enemy_hit
	track_destroyed
	track_explosion
	track_teleport_in
	track_error
	track_fake_protoman_whistle
	track_protoman_whistle
	track_lift_up_1
	track_lift_up_2
	track_train_1
	track_train_2
	track_teleport_out
	track_power_muscler
	track_taban
	track_teckyun
	track_appearing_block
	track_jump_into_water
	track_kouker_q
	track_metall_cannon
	track_metall_k1000
	track_beat
	track_gravity_switch
	track_water_wave
	track_gyro_attack
	track_chargeman_launch
	track_power_stone
	track_gravity_hold
	track_sumatran
	track_46
	track_dachone_walking
	track_dachone_laser
	track_title
	track_escape
	track_get_weapon_energy
.ENDENUM
