.SEGMENT "BANK00"
.INCLUDE "constants/tsa.asm"
.INCBIN  "stages/gravityman/0.bin"
.INCLUDE "stages/gravityman/gravityman_tsa.asm"
.INCLUDE "stages/gravityman/gravityman_mapset.asm"

.SEGMENT "BANK01"
.INCBIN  "stages/waveman/1.bin"
.INCLUDE "stages/waveman/waveman_tsa.asm"
.INCLUDE "stages/waveman/waveman_mapset.asm"

.SEGMENT "BANK02"
.INCBIN  "stages/stoneman/2.bin"
.INCLUDE "stages/stoneman/stoneman_tsa.asm"
.INCLUDE "stages/stoneman/stoneman_mapset.asm"

.SEGMENT "BANK03"
.INCBIN  "stages/gyroman/3.bin"
.INCLUDE "stages/gyroman/gyroman_tsa.asm"
.INCLUDE "stages/gyroman/gyroman_mapset.asm"

.SEGMENT "BANK04"
.INCBIN  "stages/starman/4.bin"
.INCLUDE "stages/starman/starman_tsa.asm"
.INCLUDE "stages/starman/starman_mapset.asm"

.SEGMENT "BANK05"
.INCBIN  "stages/chargeman/5.bin"
.INCLUDE "stages/chargeman/chargeman_tsa.asm"
.INCLUDE "stages/chargeman/chargeman_mapset.asm"

.SEGMENT "BANK06"
.INCBIN  "stages/napalmman/6.bin"
.INCLUDE "stages/napalmman/napalmman_tsa.asm"
.INCLUDE "stages/napalmman/napalmman_mapset.asm"

.SEGMENT "BANK07"
.INCBIN  "stages/crystalman/7.bin"
.INCLUDE "stages/crystalman/crystalman_tsa.asm"
.INCLUDE "stages/crystalman/crystalman_mapset.asm"

.SEGMENT "BANK08"
.INCBIN  "stages/darkman1_4/8.bin"
.INCLUDE "stages/darkman1_4/darkman1_4_tsa.asm"
.INCLUDE "stages/darkman1_4/darkman1_4_mapset.asm"

.SEGMENT "BANK09"
.INCBIN  "stages/darkman2/9.bin"
.INCLUDE "stages/darkman2/darkman2_tsa.asm"
.INCLUDE "stages/darkman2/darkman2_mapset.asm"

.SEGMENT "BANK0A"
.INCBIN  "stages/darkman3/10.bin"
.INCLUDE "stages/darkman3/darkman3_tsa.asm"
.INCLUDE "stages/darkman3/darkman3_mapset.asm"

.SEGMENT "BANK0C"
.INCBIN  "stages/wily1/12.bin"
.INCLUDE "stages/wily1/wily1_tsa.asm"
.INCLUDE "stages/wily1/wily1_mapset.asm"

.SEGMENT "BANK0D"
.INCBIN  "stages/wily2/13.bin"
.INCLUDE "stages/wily2/wily2_tsa.asm"
.INCLUDE "stages/wily2/wily2_mapset.asm"

.SEGMENT "BANK0E"
.INCBIN  "stages/wily3_4/14.bin"
.INCLUDE "stages/wily3_4/wily3_4_tsa.asm"
.INCLUDE "stages/wily3_4/wily3_4_mapset.asm"
