base $8000
incsrc audio.asm
incsrc track_data_pointers.asm
incsrc instruments.asm
incsrc .\music\gravity.asm
incsrc .\music\stone.asm
incsrc .\music\wave.asm
incsrc .\music\star.asm
incsrc .\music\crystal.asm
incsrc .\music\gyro.asm
incsrc .\music\charge.asm
incsrc .\music\napalm.asm
incsrc .\music\dark.asm
incsrc .\music\wily.asm
incsrc .\music\boss.asm
incsrc .\music\opening.asm
incsrc .\music\ending.asm
incsrc .\music\stage_select.asm
incsrc .\music\game_start.asm
incsrc .\music\dark_map.asm
incsrc .\music\wily_map.asm
incsrc .\music\stage_clear.asm
incsrc .\music\game_over.asm
incsrc .\music\pass_word.asm
incsrc .\music\get_weapon.asm
incsrc .\music\all_stage_clear.asm
incsrc .\music\last_boss.asm
incsrc .\sfx\lighting.asm
incsrc .\sfx\routine_map.asm
incsrc .\sfx\ufo.asm
incsrc .\sfx\shoot.asm
incsrc .\sfx\landing.asm
incsrc .\sfx\damage_mm.asm
incsrc .\sfx\death.asm
incsrc .\sfx\shoot_recoil.asm
incsrc .\sfx\pipe.asm
incsrc .\sfx\half_charged_shoot.asm
incsrc .\sfx\fully_charged_shoot.asm
incsrc .\sfx\charge_buster.asm
incsrc .\sfx\charge_kick.asm
incsrc .\sfx\1up.asm
incsrc .\sfx\boss_door.asm
incsrc .\sfx\gain_bar.asm
incsrc .\sfx\change_weapon.asm
incsrc .\sfx\close_menu.asm
incsrc .\sfx\open_menu.asm
incsrc .\sfx\damage_boss.asm
incsrc .\sfx\destroy_enemy.asm
incsrc .\sfx\explosion.asm
incsrc .\sfx\teleport_in.asm
incsrc .\sfx\password_wrong.asm
incsrc .\music\fake_proto_whistle.asm
incsrc .\music\proto_whistle.asm
incsrc .\sfx\lift_up.asm
incsrc .\sfx\life_slow.asm
incsrc .\sfx\train_1.asm
incsrc .\sfx\train_2.asm
incsrc .\sfx\teleport_out.asm
incsrc .\sfx\power_muscler.asm
incsrc .\sfx\taban.asm
incsrc .\sfx\teckyun.asm
incsrc .\sfx\yoku_block.asm
incsrc .\sfx\water.asm
incsrc .\sfx\enemy_falling.asm
incsrc .\sfx\metall_cannon.asm
incsrc .\sfx\metallk1000.asm
incsrc .\sfx\beat.asm
incsrc .\sfx\gravity_switch.asm
incsrc .\sfx\water_wave.asm
incsrc .\sfx\gyro_attack.asm
incsrc .\sfx\charge_up.asm
incsrc .\sfx\power_stone.asm
incsrc .\sfx\gravity_hold.asm
incsrc .\sfx\sumatran.asm
incsrc .\unused\unused46.asm
incsrc .\sfx\dachone_walking.asm
incsrc .\sfx\dachone_shoot.asm
incsrc .\music\title.asm
incsrc .\music\escape.asm
incsrc .\sfx\get_weapon_energy.asm
incsrc .\unused\unused358d5.asm