track_pointers:
	.DBYT music_gravityman
	.DBYT music_stoneman
	.DBYT music_waveman
	.DBYT music_starman
	.DBYT music_crystalman
	.DBYT music_gyroman
	.DBYT music_chargeman
	.DBYT music_napalmman
	.DBYT music_darkman
	.DBYT music_wily
	.DBYT music_boss_fighting
	.DBYT music_opening
	.DBYT music_ending
	.DBYT music_stage_select
	.DBYT music_boss_show
	.DBYT music_darkman_castle
	.DBYT music_wily_castle
	.DBYT music_boss_defeated
	.DBYT music_game_over
	.DBYT music_password
	.DBYT music_get_weapon
	.DBYT music_wily_defeated
	.DBYT music_wily_fighting
	.DBYT sfx_lighting
	.DBYT sfx_route
	.DBYT sfx_wily_ufo
	.DBYT sfx_mega_buster
	.DBYT sfx_landing
	.DBYT sfx_megaman_hit
	.DBYT sfx_death
	.DBYT sfx_enemy_immune
	.DBYT sfx_pipe
	.DBYT sfx_half_charge_shot
	.DBYT sfx_full_charge_shot
	.DBYT sfx_charge_shot_full_charging
	.DBYT sfx_charge_kick
	.DBYT sfx_1up
	.DBYT sfx_door
	.DBYT sfx_refill
	.DBYT sfx_select
	.DBYT sfx_confirm
	.DBYT sfx_open_menu
	.DBYT sfx_enemy_hit
	.DBYT sfx_destroyed
	.DBYT sfx_explosion
	.DBYT sfx_teleport_in
	.DBYT sfx_error
	.DBYT music_fake_protoman_whistle
	.DBYT music_protoman_whistle
	.DBYT sfx_lift_up_1
	.DBYT sfx_lift_up_2
	.DBYT sfx_train_1
	.DBYT sfx_train_2
	.DBYT sfx_teleport_out
	.DBYT sfx_power_muscler
	.DBYT sfx_taban
	.DBYT sfx_teckyun
	.DBYT sfx_appearing_block
	.DBYT sfx_jump_into_water
	.DBYT sfx_kouker_q
	.DBYT sfx_metall_cannon
	.DBYT sfx_metall_k1000
	.DBYT sfx_beat
	.DBYT sfx_gravity_switch
	.DBYT sfx_water_wave
	.DBYT sfx_gyro_attack
	.DBYT sfx_chargeman_launch
	.DBYT sfx_power_stone
	.DBYT sfx_gravity_hold
	.DBYT sfx_sumatran
	.DBYT sfx_46
	.DBYT sfx_dachone_walking
	.DBYT sfx_dachone_laser
	.DBYT music_title
	.DBYT music_escape
	.DBYT sfx_get_weapon_energy
track_pointers_end:
