oam_sprites_lo_pointers:
	.LOBYTES oam_sprites_000
	.LOBYTES oam_sprites_001
	.LOBYTES oam_sprites_002
	.LOBYTES oam_sprites_003
	.LOBYTES oam_sprites_004
	.LOBYTES oam_sprites_005
	.LOBYTES oam_sprites_006
	.LOBYTES oam_sprites_007
	.LOBYTES oam_sprites_008
	.LOBYTES oam_sprites_009
	.LOBYTES oam_sprites_00a
	.LOBYTES oam_sprites_00b
	.LOBYTES oam_sprites_00c
	.LOBYTES oam_sprites_00d
	.LOBYTES oam_sprites_00e
	.LOBYTES oam_sprites_00f
	.LOBYTES oam_sprites_010
	.LOBYTES oam_sprites_011
	.LOBYTES oam_sprites_012
	.LOBYTES oam_sprites_013
	.LOBYTES oam_sprites_014
	.LOBYTES oam_sprites_015
	.LOBYTES oam_sprites_016
	.LOBYTES oam_sprites_017
	.LOBYTES oam_sprites_018
	.LOBYTES oam_sprites_019
	.LOBYTES oam_sprites_01a
	.LOBYTES oam_sprites_01b
	.LOBYTES oam_sprites_01c
	.LOBYTES oam_sprites_01d
	.LOBYTES oam_sprites_01e
	.LOBYTES oam_sprites_01f
	.LOBYTES oam_sprites_020
	.LOBYTES oam_sprites_021
	.LOBYTES oam_sprites_022
	.LOBYTES oam_sprites_023
	.LOBYTES oam_sprites_024
	.LOBYTES oam_sprites_025
	.LOBYTES oam_sprites_026
	.LOBYTES oam_sprites_027
	.LOBYTES oam_sprites_028
	.LOBYTES oam_sprites_029
	.LOBYTES oam_sprites_02a
	.LOBYTES oam_sprites_02b
	.LOBYTES oam_sprites_02c
	.LOBYTES oam_sprites_02d
	.LOBYTES oam_sprites_02e
	.LOBYTES oam_sprites_02f
	.LOBYTES oam_sprites_030
	.LOBYTES oam_sprites_031
	.LOBYTES oam_sprites_032
	.LOBYTES oam_sprites_033
	.LOBYTES oam_sprites_034
	.LOBYTES oam_sprites_035
	.LOBYTES oam_sprites_036
	.LOBYTES oam_sprites_037
	.LOBYTES oam_sprites_038
	.LOBYTES oam_sprites_039
	.LOBYTES oam_sprites_03a
	.LOBYTES oam_sprites_03b
	.LOBYTES oam_sprites_03c
	.LOBYTES oam_sprites_03d
	.LOBYTES oam_sprites_03e
	.LOBYTES oam_sprites_03f
	.LOBYTES oam_sprites_040
	.LOBYTES oam_sprites_041
	.LOBYTES oam_sprites_042
	.LOBYTES oam_sprites_043
	.LOBYTES oam_sprites_044
	.LOBYTES oam_sprites_045
	.LOBYTES oam_sprites_046
	.LOBYTES oam_sprites_047
	.LOBYTES oam_sprites_048
	.LOBYTES oam_sprites_049
	.LOBYTES oam_sprites_04a
	.LOBYTES oam_sprites_04b
	.LOBYTES oam_sprites_04c
	.LOBYTES oam_sprites_04d
	.LOBYTES oam_sprites_04e
	.LOBYTES oam_sprites_04f
	.LOBYTES oam_sprites_050
	.LOBYTES oam_sprites_051
	.LOBYTES oam_sprites_052
	.LOBYTES oam_sprites_053
	.LOBYTES oam_sprites_054
	.LOBYTES oam_sprites_055
	.LOBYTES oam_sprites_056
	.LOBYTES oam_sprites_057
	.LOBYTES oam_sprites_058
	.LOBYTES oam_sprites_059
	.LOBYTES oam_sprites_05a
	.LOBYTES oam_sprites_05b
	.LOBYTES oam_sprites_05c
	.LOBYTES oam_sprites_05d
	.LOBYTES oam_sprites_05e
	.LOBYTES oam_sprites_05f
	.LOBYTES oam_sprites_060
	.LOBYTES oam_sprites_061
	.LOBYTES oam_sprites_062
	.LOBYTES oam_sprites_063
	.LOBYTES oam_sprites_064
	.LOBYTES oam_sprites_065
	.LOBYTES oam_sprites_066
	.LOBYTES oam_sprites_067
	.LOBYTES oam_sprites_068
	.LOBYTES oam_sprites_069
	.LOBYTES oam_sprites_06a
	.LOBYTES oam_sprites_06b
	.LOBYTES oam_sprites_06c
	.LOBYTES oam_sprites_06d
	.LOBYTES oam_sprites_06e
	.LOBYTES oam_sprites_06f
	.LOBYTES oam_sprites_070
	.LOBYTES oam_sprites_071
	.LOBYTES oam_sprites_072
	.LOBYTES oam_sprites_073
	.LOBYTES oam_sprites_074
	.LOBYTES oam_sprites_075
	.LOBYTES oam_sprites_076
	.LOBYTES oam_sprites_077
	.LOBYTES oam_sprites_078
	.LOBYTES oam_sprites_079
	.LOBYTES oam_sprites_07a
	.LOBYTES oam_sprites_07b
	.LOBYTES oam_sprites_07c
	.LOBYTES oam_sprites_07d
	.LOBYTES oam_sprites_07e
	.LOBYTES oam_sprites_07f
	.LOBYTES oam_sprites_080
	.LOBYTES oam_sprites_081
	.LOBYTES oam_sprites_082
	.LOBYTES oam_sprites_083
	.LOBYTES oam_sprites_084
	.LOBYTES oam_sprites_085
	.LOBYTES oam_sprites_086
	.LOBYTES oam_sprites_087
	.LOBYTES oam_sprites_088
	.LOBYTES oam_sprites_089
	.LOBYTES oam_sprites_08a
	.LOBYTES oam_sprites_08b
	.LOBYTES oam_sprites_08c
	.LOBYTES oam_sprites_08d
	.LOBYTES oam_sprites_08e
	.LOBYTES oam_sprites_08f
	.LOBYTES oam_sprites_090
	.LOBYTES oam_sprites_091
	.LOBYTES oam_sprites_092
	.LOBYTES oam_sprites_093
	.LOBYTES oam_sprites_094
	.LOBYTES oam_sprites_095
	.LOBYTES oam_sprites_096
	.LOBYTES oam_sprites_097
	.LOBYTES oam_sprites_098
	.LOBYTES oam_sprites_099
	.LOBYTES oam_sprites_09a
	.LOBYTES oam_sprites_09b
	.LOBYTES oam_sprites_09c
	.LOBYTES oam_sprites_09d
	.LOBYTES oam_sprites_09e
	.LOBYTES oam_sprites_09f
	.LOBYTES oam_sprites_0a0
	.LOBYTES oam_sprites_0a1
	.LOBYTES oam_sprites_0a2
	.LOBYTES oam_sprites_0a3
	.LOBYTES oam_sprites_0a4
	.LOBYTES oam_sprites_0a5
	.LOBYTES oam_sprites_0a6
	.LOBYTES oam_sprites_0a7
	.LOBYTES oam_sprites_0a8
	.LOBYTES oam_sprites_0a9
	.LOBYTES oam_sprites_0aa
	.LOBYTES oam_sprites_0ab
	.LOBYTES oam_sprites_0ac
	.LOBYTES oam_sprites_0ad
	.LOBYTES oam_sprites_0ae
	.LOBYTES oam_sprites_0af
	.LOBYTES oam_sprites_0b0
	.LOBYTES oam_sprites_0b1
	.LOBYTES oam_sprites_0b2
	.LOBYTES oam_sprites_0b3
	.LOBYTES oam_sprites_0b4
	.LOBYTES oam_sprites_0b5
	.LOBYTES oam_sprites_0b6
	.LOBYTES oam_sprites_0b7
	.LOBYTES oam_sprites_0b8
	.LOBYTES oam_sprites_0b9
	.LOBYTES oam_sprites_0ba
	.LOBYTES oam_sprites_0bb
	.LOBYTES oam_sprites_0bc
	.LOBYTES oam_sprites_0bd
	.LOBYTES oam_sprites_0be
	.LOBYTES oam_sprites_0bf
	.LOBYTES oam_sprites_0c0
	.LOBYTES oam_sprites_0c1
	.LOBYTES oam_sprites_0c2
	.LOBYTES oam_sprites_0c3
	.LOBYTES oam_sprites_0c4
	.LOBYTES oam_sprites_0c5
	.LOBYTES oam_sprites_0c6
	.LOBYTES oam_sprites_0c7
	.LOBYTES oam_sprites_0c8
	.LOBYTES oam_sprites_0c9
	.LOBYTES oam_sprites_0ca
	.LOBYTES oam_sprites_0cb
	.LOBYTES oam_sprites_0cc
	.LOBYTES oam_sprites_0cd
	.LOBYTES oam_sprites_0ce
	.LOBYTES oam_sprites_0cf
	.LOBYTES oam_sprites_0d0
	.LOBYTES oam_sprites_0d1
	.LOBYTES oam_sprites_0d2
	.LOBYTES oam_sprites_0d3
	.LOBYTES oam_sprites_0d4
	.LOBYTES oam_sprites_0d5
	.LOBYTES oam_sprites_0d6
	.LOBYTES oam_sprites_0d7
	.LOBYTES oam_sprites_0d8
	.LOBYTES oam_sprites_0d9
	.LOBYTES oam_sprites_0da
	.LOBYTES oam_sprites_0db
	.LOBYTES oam_sprites_0dc
	.LOBYTES oam_sprites_0dd
	.LOBYTES oam_sprites_0de
	.LOBYTES oam_sprites_0df
	.LOBYTES oam_sprites_0e0
	.LOBYTES oam_sprites_0e1
	.LOBYTES oam_sprites_0e2
	.LOBYTES oam_sprites_0e3
	.LOBYTES oam_sprites_0e4
	.LOBYTES oam_sprites_0e5
	.LOBYTES oam_sprites_0e6
	.LOBYTES oam_sprites_0e7
	.LOBYTES oam_sprites_0e8
	.LOBYTES oam_sprites_0e9
	.LOBYTES oam_sprites_0ea
	.LOBYTES oam_sprites_0eb
	.LOBYTES oam_sprites_0ec
	.LOBYTES oam_sprites_0ed
	.LOBYTES oam_sprites_0ee
	.LOBYTES oam_sprites_0ef
	.LOBYTES oam_sprites_0f0
	.LOBYTES oam_sprites_0f1
	.LOBYTES oam_sprites_0f2
	.LOBYTES oam_sprites_0f3
	.LOBYTES oam_sprites_0f4
	.LOBYTES oam_sprites_0f5
	.LOBYTES oam_sprites_0f6
	.LOBYTES oam_sprites_0f7
	.LOBYTES oam_sprites_0f8
	.LOBYTES oam_sprites_0f9
	.LOBYTES oam_sprites_0fa
	.LOBYTES oam_sprites_0fb
	.LOBYTES oam_sprites_0fc
	.LOBYTES oam_sprites_0fd
	.LOBYTES oam_sprites_0fe
	.LOBYTES oam_sprites_0ff
	.LOBYTES oam_sprites_100
	.LOBYTES oam_sprites_101
	.LOBYTES oam_sprites_102
	.LOBYTES oam_sprites_103
	.LOBYTES oam_sprites_104
	.LOBYTES oam_sprites_105
	.LOBYTES oam_sprites_106
	.LOBYTES oam_sprites_107
	.LOBYTES oam_sprites_108
	.LOBYTES oam_sprites_109
	.LOBYTES oam_sprites_10a
	.LOBYTES oam_sprites_10b
	.LOBYTES oam_sprites_10c
	.LOBYTES oam_sprites_10d
	.LOBYTES oam_sprites_10e
	.LOBYTES oam_sprites_10f
	.LOBYTES oam_sprites_110
	.LOBYTES oam_sprites_111
	.LOBYTES oam_sprites_112
	.LOBYTES oam_sprites_113
	.LOBYTES oam_sprites_114
	.LOBYTES oam_sprites_115
	.LOBYTES oam_sprites_116
	.LOBYTES oam_sprites_117
	.LOBYTES oam_sprites_118
	.LOBYTES oam_sprites_119
	.LOBYTES oam_sprites_11a
	.LOBYTES oam_sprites_11b
	.LOBYTES oam_sprites_11c
	.LOBYTES oam_sprites_11d
	.LOBYTES oam_sprites_11e
	.LOBYTES oam_sprites_11f
	.LOBYTES oam_sprites_120
	.LOBYTES oam_sprites_121
	.LOBYTES oam_sprites_122
	.LOBYTES oam_sprites_123
	.LOBYTES oam_sprites_124
	.LOBYTES oam_sprites_125
	.LOBYTES oam_sprites_126
	.LOBYTES oam_sprites_127
	.LOBYTES oam_sprites_128
	.LOBYTES oam_sprites_129
	.LOBYTES oam_sprites_12a
	.LOBYTES oam_sprites_12b
	.LOBYTES oam_sprites_12c
	.LOBYTES oam_sprites_12d
	.LOBYTES oam_sprites_12e
	.LOBYTES oam_sprites_12f
	.LOBYTES oam_sprites_130
	.LOBYTES oam_sprites_131
	.LOBYTES oam_sprites_132
	.LOBYTES oam_sprites_133
	.LOBYTES oam_sprites_134
	.LOBYTES oam_sprites_135
	.LOBYTES oam_sprites_136
	.LOBYTES oam_sprites_137
	.LOBYTES oam_sprites_138
	.LOBYTES oam_sprites_139
	.LOBYTES oam_sprites_13a
	.LOBYTES oam_sprites_13b
	.LOBYTES oam_sprites_13c
	.LOBYTES oam_sprites_13d
	.LOBYTES oam_sprites_13e
	.LOBYTES oam_sprites_13f
	.LOBYTES oam_sprites_140
	.LOBYTES oam_sprites_141
	.LOBYTES oam_sprites_142
	.LOBYTES oam_sprites_143
	.LOBYTES oam_sprites_144
	.LOBYTES oam_sprites_145
	.LOBYTES oam_sprites_146
	.LOBYTES oam_sprites_147
	.LOBYTES oam_sprites_148
	.LOBYTES oam_sprites_149
	.LOBYTES oam_sprites_14a
	.LOBYTES oam_sprites_14b
	.LOBYTES oam_sprites_14c
	.LOBYTES oam_sprites_14d
	.LOBYTES oam_sprites_14e
	.LOBYTES oam_sprites_14f
	.LOBYTES oam_sprites_150
	.LOBYTES oam_sprites_151
	.LOBYTES oam_sprites_152
	.LOBYTES oam_sprites_153
	.LOBYTES oam_sprites_154
	.LOBYTES oam_sprites_155
	.LOBYTES oam_sprites_156
	.LOBYTES oam_sprites_157
	.LOBYTES oam_sprites_158
	.LOBYTES oam_sprites_159
	.LOBYTES oam_sprites_15a
	.LOBYTES oam_sprites_15b
	.LOBYTES oam_sprites_15c
	.LOBYTES oam_sprites_15d
	.LOBYTES oam_sprites_15e
	.LOBYTES oam_sprites_15f
	.LOBYTES oam_sprites_160
	.LOBYTES oam_sprites_161
	.LOBYTES oam_sprites_162
	.LOBYTES oam_sprites_163
	.LOBYTES oam_sprites_164
	.LOBYTES oam_sprites_165
	.LOBYTES oam_sprites_166
	.LOBYTES oam_sprites_167
	.LOBYTES oam_sprites_168
	.LOBYTES oam_sprites_169
	.LOBYTES oam_sprites_16a
	.LOBYTES oam_sprites_16b
	.LOBYTES oam_sprites_16c
	.LOBYTES oam_sprites_16d
	.LOBYTES oam_sprites_16e
	.LOBYTES oam_sprites_16f
	.LOBYTES oam_sprites_170
	.LOBYTES oam_sprites_171
	.LOBYTES oam_sprites_172
	.LOBYTES oam_sprites_173
	.LOBYTES oam_sprites_174
	.LOBYTES oam_sprites_175
	.LOBYTES oam_sprites_176
	.LOBYTES oam_sprites_177
	.LOBYTES oam_sprites_178
	.LOBYTES oam_sprites_179
	.LOBYTES oam_sprites_17a
	.LOBYTES oam_sprites_17b
	.LOBYTES oam_sprites_17c
	.LOBYTES oam_sprites_17d
	.LOBYTES oam_sprites_17e
	.LOBYTES oam_sprites_17f
	.LOBYTES oam_sprites_180
	.LOBYTES oam_sprites_181
	.LOBYTES oam_sprites_182
	.LOBYTES oam_sprites_183
	.LOBYTES oam_sprites_184
	.LOBYTES oam_sprites_185
	.LOBYTES oam_sprites_186
	.LOBYTES oam_sprites_187
	.LOBYTES oam_sprites_188
	.LOBYTES oam_sprites_189
	.LOBYTES oam_sprites_18a
	.LOBYTES oam_sprites_18b
	.LOBYTES oam_sprites_18c
	.LOBYTES oam_sprites_18d
	.LOBYTES oam_sprites_18e
	.LOBYTES oam_sprites_18f
	.LOBYTES oam_sprites_190
	.LOBYTES oam_sprites_191
	.LOBYTES oam_sprites_192
	.LOBYTES oam_sprites_193
	.LOBYTES oam_sprites_194
	.LOBYTES oam_sprites_195
	.LOBYTES oam_sprites_196
	.LOBYTES oam_sprites_197
	.LOBYTES oam_sprites_198
	.LOBYTES oam_sprites_199
	.LOBYTES oam_sprites_19a
	.LOBYTES oam_sprites_19b
	.LOBYTES oam_sprites_19c
	.LOBYTES oam_sprites_19d
	.LOBYTES oam_sprites_19e
	.LOBYTES oam_sprites_19f
	.LOBYTES oam_sprites_1a0
	.LOBYTES oam_sprites_1a1
	.LOBYTES oam_sprites_1a2
	.LOBYTES oam_sprites_1a3
	.LOBYTES oam_sprites_1a4
	.LOBYTES oam_sprites_1a5
	.LOBYTES oam_sprites_1a6
	.LOBYTES oam_sprites_1a7
	.LOBYTES oam_sprites_1a8
	.LOBYTES oam_sprites_1a9
	.LOBYTES oam_sprites_1aa
	.LOBYTES oam_sprites_1ab
	.LOBYTES oam_sprites_1ac
	.LOBYTES oam_sprites_1ad
	.LOBYTES oam_sprites_1ae
	.LOBYTES oam_sprites_1af
	.LOBYTES oam_sprites_1b0
	.LOBYTES oam_sprites_1b1
	.LOBYTES oam_sprites_1b2
	.LOBYTES oam_sprites_1b3
	.LOBYTES oam_sprites_1b4
	.LOBYTES oam_sprites_1b5
	.LOBYTES oam_sprites_1b6
	.LOBYTES oam_sprites_1b7
	.LOBYTES oam_sprites_1b8
	.LOBYTES oam_sprites_1b9
	.LOBYTES oam_sprites_1ba
	.LOBYTES oam_sprites_1bb
	.LOBYTES oam_sprites_1bc
	.LOBYTES oam_sprites_1bd
	.LOBYTES oam_sprites_1be
	.LOBYTES oam_sprites_1bf
	.LOBYTES oam_sprites_1c0
	.LOBYTES oam_sprites_1c1
	.LOBYTES oam_sprites_1c2
	.LOBYTES oam_sprites_1c3
	.LOBYTES oam_sprites_1c4
	.LOBYTES oam_sprites_1c5
	.LOBYTES oam_sprites_1c6
	.LOBYTES oam_sprites_1c7
	.LOBYTES oam_sprites_1c8
	.LOBYTES oam_sprites_1c9
	.LOBYTES oam_sprites_1ca
	.LOBYTES oam_sprites_1cb
	.LOBYTES oam_sprites_1cc
	.LOBYTES oam_sprites_1cd
	.LOBYTES oam_sprites_1ce
	.LOBYTES oam_sprites_1cf
	.LOBYTES oam_sprites_1d0
	.LOBYTES oam_sprites_1d1
	.LOBYTES oam_sprites_1d2
	.LOBYTES oam_sprites_1d3
	.LOBYTES oam_sprites_1d4
	.LOBYTES oam_sprites_1d5
	.LOBYTES oam_sprites_1d6
	.LOBYTES oam_sprites_1d7
	.LOBYTES oam_sprites_1d8
	.LOBYTES oam_sprites_1d9
	.LOBYTES oam_sprites_1da
	.LOBYTES oam_sprites_1db
	.LOBYTES oam_sprites_1dc
	.LOBYTES oam_sprites_1dd
	.LOBYTES oam_sprites_1de
	.LOBYTES oam_sprites_1df
	.LOBYTES oam_sprites_1e0
	.LOBYTES oam_sprites_1e1
	.LOBYTES oam_sprites_1e2
	.LOBYTES oam_sprites_1e3
	.LOBYTES oam_sprites_1e4
	.LOBYTES oam_sprites_1e5
	.LOBYTES oam_sprites_1e6
	.LOBYTES oam_sprites_1e7
	.LOBYTES oam_sprites_1e8
	.LOBYTES oam_sprites_1e9
	.LOBYTES oam_sprites_1ea
	.LOBYTES oam_sprites_1eb
	.LOBYTES oam_sprites_1ec
	.LOBYTES oam_sprites_1ed
	.LOBYTES oam_sprites_1ee
	.LOBYTES oam_sprites_1ef

;unused
	.BYTE $BF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FE, $FF, $FF, $FF, $FF, $FF

oam_sprites_hi_pointers:
	.HIBYTES oam_sprites_000
	.HIBYTES oam_sprites_001
	.HIBYTES oam_sprites_002
	.HIBYTES oam_sprites_003
	.HIBYTES oam_sprites_004
	.HIBYTES oam_sprites_005
	.HIBYTES oam_sprites_006
	.HIBYTES oam_sprites_007
	.HIBYTES oam_sprites_008
	.HIBYTES oam_sprites_009
	.HIBYTES oam_sprites_00a
	.HIBYTES oam_sprites_00b
	.HIBYTES oam_sprites_00c
	.HIBYTES oam_sprites_00d
	.HIBYTES oam_sprites_00e
	.HIBYTES oam_sprites_00f
	.HIBYTES oam_sprites_010
	.HIBYTES oam_sprites_011
	.HIBYTES oam_sprites_012
	.HIBYTES oam_sprites_013
	.HIBYTES oam_sprites_014
	.HIBYTES oam_sprites_015
	.HIBYTES oam_sprites_016
	.HIBYTES oam_sprites_017
	.HIBYTES oam_sprites_018
	.HIBYTES oam_sprites_019
	.HIBYTES oam_sprites_01a
	.HIBYTES oam_sprites_01b
	.HIBYTES oam_sprites_01c
	.HIBYTES oam_sprites_01d
	.HIBYTES oam_sprites_01e
	.HIBYTES oam_sprites_01f
	.HIBYTES oam_sprites_020
	.HIBYTES oam_sprites_021
	.HIBYTES oam_sprites_022
	.HIBYTES oam_sprites_023
	.HIBYTES oam_sprites_024
	.HIBYTES oam_sprites_025
	.HIBYTES oam_sprites_026
	.HIBYTES oam_sprites_027
	.HIBYTES oam_sprites_028
	.HIBYTES oam_sprites_029
	.HIBYTES oam_sprites_02a
	.HIBYTES oam_sprites_02b
	.HIBYTES oam_sprites_02c
	.HIBYTES oam_sprites_02d
	.HIBYTES oam_sprites_02e
	.HIBYTES oam_sprites_02f
	.HIBYTES oam_sprites_030
	.HIBYTES oam_sprites_031
	.HIBYTES oam_sprites_032
	.HIBYTES oam_sprites_033
	.HIBYTES oam_sprites_034
	.HIBYTES oam_sprites_035
	.HIBYTES oam_sprites_036
	.HIBYTES oam_sprites_037
	.HIBYTES oam_sprites_038
	.HIBYTES oam_sprites_039
	.HIBYTES oam_sprites_03a
	.HIBYTES oam_sprites_03b
	.HIBYTES oam_sprites_03c
	.HIBYTES oam_sprites_03d
	.HIBYTES oam_sprites_03e
	.HIBYTES oam_sprites_03f
	.HIBYTES oam_sprites_040
	.HIBYTES oam_sprites_041
	.HIBYTES oam_sprites_042
	.HIBYTES oam_sprites_043
	.HIBYTES oam_sprites_044
	.HIBYTES oam_sprites_045
	.HIBYTES oam_sprites_046
	.HIBYTES oam_sprites_047
	.HIBYTES oam_sprites_048
	.HIBYTES oam_sprites_049
	.HIBYTES oam_sprites_04a
	.HIBYTES oam_sprites_04b
	.HIBYTES oam_sprites_04c
	.HIBYTES oam_sprites_04d
	.HIBYTES oam_sprites_04e
	.HIBYTES oam_sprites_04f
	.HIBYTES oam_sprites_050
	.HIBYTES oam_sprites_051
	.HIBYTES oam_sprites_052
	.HIBYTES oam_sprites_053
	.HIBYTES oam_sprites_054
	.HIBYTES oam_sprites_055
	.HIBYTES oam_sprites_056
	.HIBYTES oam_sprites_057
	.HIBYTES oam_sprites_058
	.HIBYTES oam_sprites_059
	.HIBYTES oam_sprites_05a
	.HIBYTES oam_sprites_05b
	.HIBYTES oam_sprites_05c
	.HIBYTES oam_sprites_05d
	.HIBYTES oam_sprites_05e
	.HIBYTES oam_sprites_05f
	.HIBYTES oam_sprites_060
	.HIBYTES oam_sprites_061
	.HIBYTES oam_sprites_062
	.HIBYTES oam_sprites_063
	.HIBYTES oam_sprites_064
	.HIBYTES oam_sprites_065
	.HIBYTES oam_sprites_066
	.HIBYTES oam_sprites_067
	.HIBYTES oam_sprites_068
	.HIBYTES oam_sprites_069
	.HIBYTES oam_sprites_06a
	.HIBYTES oam_sprites_06b
	.HIBYTES oam_sprites_06c
	.HIBYTES oam_sprites_06d
	.HIBYTES oam_sprites_06e
	.HIBYTES oam_sprites_06f
	.HIBYTES oam_sprites_070
	.HIBYTES oam_sprites_071
	.HIBYTES oam_sprites_072
	.HIBYTES oam_sprites_073
	.HIBYTES oam_sprites_074
	.HIBYTES oam_sprites_075
	.HIBYTES oam_sprites_076
	.HIBYTES oam_sprites_077
	.HIBYTES oam_sprites_078
	.HIBYTES oam_sprites_079
	.HIBYTES oam_sprites_07a
	.HIBYTES oam_sprites_07b
	.HIBYTES oam_sprites_07c
	.HIBYTES oam_sprites_07d
	.HIBYTES oam_sprites_07e
	.HIBYTES oam_sprites_07f
	.HIBYTES oam_sprites_080
	.HIBYTES oam_sprites_081
	.HIBYTES oam_sprites_082
	.HIBYTES oam_sprites_083
	.HIBYTES oam_sprites_084
	.HIBYTES oam_sprites_085
	.HIBYTES oam_sprites_086
	.HIBYTES oam_sprites_087
	.HIBYTES oam_sprites_088
	.HIBYTES oam_sprites_089
	.HIBYTES oam_sprites_08a
	.HIBYTES oam_sprites_08b
	.HIBYTES oam_sprites_08c
	.HIBYTES oam_sprites_08d
	.HIBYTES oam_sprites_08e
	.HIBYTES oam_sprites_08f
	.HIBYTES oam_sprites_090
	.HIBYTES oam_sprites_091
	.HIBYTES oam_sprites_092
	.HIBYTES oam_sprites_093
	.HIBYTES oam_sprites_094
	.HIBYTES oam_sprites_095
	.HIBYTES oam_sprites_096
	.HIBYTES oam_sprites_097
	.HIBYTES oam_sprites_098
	.HIBYTES oam_sprites_099
	.HIBYTES oam_sprites_09a
	.HIBYTES oam_sprites_09b
	.HIBYTES oam_sprites_09c
	.HIBYTES oam_sprites_09d
	.HIBYTES oam_sprites_09e
	.HIBYTES oam_sprites_09f
	.HIBYTES oam_sprites_0a0
	.HIBYTES oam_sprites_0a1
	.HIBYTES oam_sprites_0a2
	.HIBYTES oam_sprites_0a3
	.HIBYTES oam_sprites_0a4
	.HIBYTES oam_sprites_0a5
	.HIBYTES oam_sprites_0a6
	.HIBYTES oam_sprites_0a7
	.HIBYTES oam_sprites_0a8
	.HIBYTES oam_sprites_0a9
	.HIBYTES oam_sprites_0aa
	.HIBYTES oam_sprites_0ab
	.HIBYTES oam_sprites_0ac
	.HIBYTES oam_sprites_0ad
	.HIBYTES oam_sprites_0ae
	.HIBYTES oam_sprites_0af
	.HIBYTES oam_sprites_0b0
	.HIBYTES oam_sprites_0b1
	.HIBYTES oam_sprites_0b2
	.HIBYTES oam_sprites_0b3
	.HIBYTES oam_sprites_0b4
	.HIBYTES oam_sprites_0b5
	.HIBYTES oam_sprites_0b6
	.HIBYTES oam_sprites_0b7
	.HIBYTES oam_sprites_0b8
	.HIBYTES oam_sprites_0b9
	.HIBYTES oam_sprites_0ba
	.HIBYTES oam_sprites_0bb
	.HIBYTES oam_sprites_0bc
	.HIBYTES oam_sprites_0bd
	.HIBYTES oam_sprites_0be
	.HIBYTES oam_sprites_0bf
	.HIBYTES oam_sprites_0c0
	.HIBYTES oam_sprites_0c1
	.HIBYTES oam_sprites_0c2
	.HIBYTES oam_sprites_0c3
	.HIBYTES oam_sprites_0c4
	.HIBYTES oam_sprites_0c5
	.HIBYTES oam_sprites_0c6
	.HIBYTES oam_sprites_0c7
	.HIBYTES oam_sprites_0c8
	.HIBYTES oam_sprites_0c9
	.HIBYTES oam_sprites_0ca
	.HIBYTES oam_sprites_0cb
	.HIBYTES oam_sprites_0cc
	.HIBYTES oam_sprites_0cd
	.HIBYTES oam_sprites_0ce
	.HIBYTES oam_sprites_0cf
	.HIBYTES oam_sprites_0d0
	.HIBYTES oam_sprites_0d1
	.HIBYTES oam_sprites_0d2
	.HIBYTES oam_sprites_0d3
	.HIBYTES oam_sprites_0d4
	.HIBYTES oam_sprites_0d5
	.HIBYTES oam_sprites_0d6
	.HIBYTES oam_sprites_0d7
	.HIBYTES oam_sprites_0d8
	.HIBYTES oam_sprites_0d9
	.HIBYTES oam_sprites_0da
	.HIBYTES oam_sprites_0db
	.HIBYTES oam_sprites_0dc
	.HIBYTES oam_sprites_0dd
	.HIBYTES oam_sprites_0de
	.HIBYTES oam_sprites_0df
	.HIBYTES oam_sprites_0e0
	.HIBYTES oam_sprites_0e1
	.HIBYTES oam_sprites_0e2
	.HIBYTES oam_sprites_0e3
	.HIBYTES oam_sprites_0e4
	.HIBYTES oam_sprites_0e5
	.HIBYTES oam_sprites_0e6
	.HIBYTES oam_sprites_0e7
	.HIBYTES oam_sprites_0e8
	.HIBYTES oam_sprites_0e9
	.HIBYTES oam_sprites_0ea
	.HIBYTES oam_sprites_0eb
	.HIBYTES oam_sprites_0ec
	.HIBYTES oam_sprites_0ed
	.HIBYTES oam_sprites_0ee
	.HIBYTES oam_sprites_0ef
	.HIBYTES oam_sprites_0f0
	.HIBYTES oam_sprites_0f1
	.HIBYTES oam_sprites_0f2
	.HIBYTES oam_sprites_0f3
	.HIBYTES oam_sprites_0f4
	.HIBYTES oam_sprites_0f5
	.HIBYTES oam_sprites_0f6
	.HIBYTES oam_sprites_0f7
	.HIBYTES oam_sprites_0f8
	.HIBYTES oam_sprites_0f9
	.HIBYTES oam_sprites_0fa
	.HIBYTES oam_sprites_0fb
	.HIBYTES oam_sprites_0fc
	.HIBYTES oam_sprites_0fd
	.HIBYTES oam_sprites_0fe
	.HIBYTES oam_sprites_0ff
	.HIBYTES oam_sprites_100
	.HIBYTES oam_sprites_101
	.HIBYTES oam_sprites_102
	.HIBYTES oam_sprites_103
	.HIBYTES oam_sprites_104
	.HIBYTES oam_sprites_105
	.HIBYTES oam_sprites_106
	.HIBYTES oam_sprites_107
	.HIBYTES oam_sprites_108
	.HIBYTES oam_sprites_109
	.HIBYTES oam_sprites_10a
	.HIBYTES oam_sprites_10b
	.HIBYTES oam_sprites_10c
	.HIBYTES oam_sprites_10d
	.HIBYTES oam_sprites_10e
	.HIBYTES oam_sprites_10f
	.HIBYTES oam_sprites_110
	.HIBYTES oam_sprites_111
	.HIBYTES oam_sprites_112
	.HIBYTES oam_sprites_113
	.HIBYTES oam_sprites_114
	.HIBYTES oam_sprites_115
	.HIBYTES oam_sprites_116
	.HIBYTES oam_sprites_117
	.HIBYTES oam_sprites_118
	.HIBYTES oam_sprites_119
	.HIBYTES oam_sprites_11a
	.HIBYTES oam_sprites_11b
	.HIBYTES oam_sprites_11c
	.HIBYTES oam_sprites_11d
	.HIBYTES oam_sprites_11e
	.HIBYTES oam_sprites_11f
	.HIBYTES oam_sprites_120
	.HIBYTES oam_sprites_121
	.HIBYTES oam_sprites_122
	.HIBYTES oam_sprites_123
	.HIBYTES oam_sprites_124
	.HIBYTES oam_sprites_125
	.HIBYTES oam_sprites_126
	.HIBYTES oam_sprites_127
	.HIBYTES oam_sprites_128
	.HIBYTES oam_sprites_129
	.HIBYTES oam_sprites_12a
	.HIBYTES oam_sprites_12b
	.HIBYTES oam_sprites_12c
	.HIBYTES oam_sprites_12d
	.HIBYTES oam_sprites_12e
	.HIBYTES oam_sprites_12f
	.HIBYTES oam_sprites_130
	.HIBYTES oam_sprites_131
	.HIBYTES oam_sprites_132
	.HIBYTES oam_sprites_133
	.HIBYTES oam_sprites_134
	.HIBYTES oam_sprites_135
	.HIBYTES oam_sprites_136
	.HIBYTES oam_sprites_137
	.HIBYTES oam_sprites_138
	.HIBYTES oam_sprites_139
	.HIBYTES oam_sprites_13a
	.HIBYTES oam_sprites_13b
	.HIBYTES oam_sprites_13c
	.HIBYTES oam_sprites_13d
	.HIBYTES oam_sprites_13e
	.HIBYTES oam_sprites_13f
	.HIBYTES oam_sprites_140
	.HIBYTES oam_sprites_141
	.HIBYTES oam_sprites_142
	.HIBYTES oam_sprites_143
	.HIBYTES oam_sprites_144
	.HIBYTES oam_sprites_145
	.HIBYTES oam_sprites_146
	.HIBYTES oam_sprites_147
	.HIBYTES oam_sprites_148
	.HIBYTES oam_sprites_149
	.HIBYTES oam_sprites_14a
	.HIBYTES oam_sprites_14b
	.HIBYTES oam_sprites_14c
	.HIBYTES oam_sprites_14d
	.HIBYTES oam_sprites_14e
	.HIBYTES oam_sprites_14f
	.HIBYTES oam_sprites_150
	.HIBYTES oam_sprites_151
	.HIBYTES oam_sprites_152
	.HIBYTES oam_sprites_153
	.HIBYTES oam_sprites_154
	.HIBYTES oam_sprites_155
	.HIBYTES oam_sprites_156
	.HIBYTES oam_sprites_157
	.HIBYTES oam_sprites_158
	.HIBYTES oam_sprites_159
	.HIBYTES oam_sprites_15a
	.HIBYTES oam_sprites_15b
	.HIBYTES oam_sprites_15c
	.HIBYTES oam_sprites_15d
	.HIBYTES oam_sprites_15e
	.HIBYTES oam_sprites_15f
	.HIBYTES oam_sprites_160
	.HIBYTES oam_sprites_161
	.HIBYTES oam_sprites_162
	.HIBYTES oam_sprites_163
	.HIBYTES oam_sprites_164
	.HIBYTES oam_sprites_165
	.HIBYTES oam_sprites_166
	.HIBYTES oam_sprites_167
	.HIBYTES oam_sprites_168
	.HIBYTES oam_sprites_169
	.HIBYTES oam_sprites_16a
	.HIBYTES oam_sprites_16b
	.HIBYTES oam_sprites_16c
	.HIBYTES oam_sprites_16d
	.HIBYTES oam_sprites_16e
	.HIBYTES oam_sprites_16f
	.HIBYTES oam_sprites_170
	.HIBYTES oam_sprites_171
	.HIBYTES oam_sprites_172
	.HIBYTES oam_sprites_173
	.HIBYTES oam_sprites_174
	.HIBYTES oam_sprites_175
	.HIBYTES oam_sprites_176
	.HIBYTES oam_sprites_177
	.HIBYTES oam_sprites_178
	.HIBYTES oam_sprites_179
	.HIBYTES oam_sprites_17a
	.HIBYTES oam_sprites_17b
	.HIBYTES oam_sprites_17c
	.HIBYTES oam_sprites_17d
	.HIBYTES oam_sprites_17e
	.HIBYTES oam_sprites_17f
	.HIBYTES oam_sprites_180
	.HIBYTES oam_sprites_181
	.HIBYTES oam_sprites_182
	.HIBYTES oam_sprites_183
	.HIBYTES oam_sprites_184
	.HIBYTES oam_sprites_185
	.HIBYTES oam_sprites_186
	.HIBYTES oam_sprites_187
	.HIBYTES oam_sprites_188
	.HIBYTES oam_sprites_189
	.HIBYTES oam_sprites_18a
	.HIBYTES oam_sprites_18b
	.HIBYTES oam_sprites_18c
	.HIBYTES oam_sprites_18d
	.HIBYTES oam_sprites_18e
	.HIBYTES oam_sprites_18f
	.HIBYTES oam_sprites_190
	.HIBYTES oam_sprites_191
	.HIBYTES oam_sprites_192
	.HIBYTES oam_sprites_193
	.HIBYTES oam_sprites_194
	.HIBYTES oam_sprites_195
	.HIBYTES oam_sprites_196
	.HIBYTES oam_sprites_197
	.HIBYTES oam_sprites_198
	.HIBYTES oam_sprites_199
	.HIBYTES oam_sprites_19a
	.HIBYTES oam_sprites_19b
	.HIBYTES oam_sprites_19c
	.HIBYTES oam_sprites_19d
	.HIBYTES oam_sprites_19e
	.HIBYTES oam_sprites_19f
	.HIBYTES oam_sprites_1a0
	.HIBYTES oam_sprites_1a1
	.HIBYTES oam_sprites_1a2
	.HIBYTES oam_sprites_1a3
	.HIBYTES oam_sprites_1a4
	.HIBYTES oam_sprites_1a5
	.HIBYTES oam_sprites_1a6
	.HIBYTES oam_sprites_1a7
	.HIBYTES oam_sprites_1a8
	.HIBYTES oam_sprites_1a9
	.HIBYTES oam_sprites_1aa
	.HIBYTES oam_sprites_1ab
	.HIBYTES oam_sprites_1ac
	.HIBYTES oam_sprites_1ad
	.HIBYTES oam_sprites_1ae
	.HIBYTES oam_sprites_1af
	.HIBYTES oam_sprites_1b0
	.HIBYTES oam_sprites_1b1
	.HIBYTES oam_sprites_1b2
	.HIBYTES oam_sprites_1b3
	.HIBYTES oam_sprites_1b4
	.HIBYTES oam_sprites_1b5
	.HIBYTES oam_sprites_1b6
	.HIBYTES oam_sprites_1b7
	.HIBYTES oam_sprites_1b8
	.HIBYTES oam_sprites_1b9
	.HIBYTES oam_sprites_1ba
	.HIBYTES oam_sprites_1bb
	.HIBYTES oam_sprites_1bc
	.HIBYTES oam_sprites_1bd
	.HIBYTES oam_sprites_1be
	.HIBYTES oam_sprites_1bf
	.HIBYTES oam_sprites_1c0
	.HIBYTES oam_sprites_1c1
	.HIBYTES oam_sprites_1c2
	.HIBYTES oam_sprites_1c3
	.HIBYTES oam_sprites_1c4
	.HIBYTES oam_sprites_1c5
	.HIBYTES oam_sprites_1c6
	.HIBYTES oam_sprites_1c7
	.HIBYTES oam_sprites_1c8
	.HIBYTES oam_sprites_1c9
	.HIBYTES oam_sprites_1ca
	.HIBYTES oam_sprites_1cb
	.HIBYTES oam_sprites_1cc
	.HIBYTES oam_sprites_1cd
	.HIBYTES oam_sprites_1ce
	.HIBYTES oam_sprites_1cf
	.HIBYTES oam_sprites_1d0
	.HIBYTES oam_sprites_1d1
	.HIBYTES oam_sprites_1d2
	.HIBYTES oam_sprites_1d3
	.HIBYTES oam_sprites_1d4
	.HIBYTES oam_sprites_1d5
	.HIBYTES oam_sprites_1d6
	.HIBYTES oam_sprites_1d7
	.HIBYTES oam_sprites_1d8
	.HIBYTES oam_sprites_1d9
	.HIBYTES oam_sprites_1da
	.HIBYTES oam_sprites_1db
	.HIBYTES oam_sprites_1dc
	.HIBYTES oam_sprites_1dd
	.HIBYTES oam_sprites_1de
	.HIBYTES oam_sprites_1df
	.HIBYTES oam_sprites_1e0
	.HIBYTES oam_sprites_1e1
	.HIBYTES oam_sprites_1e2
	.HIBYTES oam_sprites_1e3
	.HIBYTES oam_sprites_1e4
	.HIBYTES oam_sprites_1e5
	.HIBYTES oam_sprites_1e6
	.HIBYTES oam_sprites_1e7
	.HIBYTES oam_sprites_1e8
	.HIBYTES oam_sprites_1e9
	.HIBYTES oam_sprites_1ea
	.HIBYTES oam_sprites_1eb
	.HIBYTES oam_sprites_1ec
	.HIBYTES oam_sprites_1ed
	.HIBYTES oam_sprites_1ee
	.HIBYTES oam_sprites_1ef

;unused
	.BYTE $FF, $FF, $FE, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FE, $FF
