oam_frameset_lo_pointers:
	.LOBYTES oam_frameset_00
	.LOBYTES oam_frameset_01
	.LOBYTES oam_frameset_02
	.LOBYTES oam_frameset_03
	.LOBYTES oam_frameset_04
	.LOBYTES oam_frameset_05
	.LOBYTES oam_frameset_06
	.LOBYTES oam_frameset_07
	.LOBYTES oam_frameset_08
	.LOBYTES oam_frameset_09
	.LOBYTES oam_frameset_0a
	.LOBYTES oam_frameset_0b
	.LOBYTES oam_frameset_0c
	.LOBYTES oam_frameset_0d
	.LOBYTES oam_frameset_0e
	.LOBYTES oam_frameset_0f
	.LOBYTES oam_frameset_10
	.LOBYTES oam_frameset_11
	.LOBYTES oam_frameset_12
	.LOBYTES oam_frameset_13
	.LOBYTES oam_frameset_14
	.LOBYTES oam_frameset_15
	.LOBYTES oam_frameset_16
	.LOBYTES oam_frameset_17
	.LOBYTES oam_frameset_18
	.LOBYTES oam_frameset_19
	.LOBYTES oam_frameset_1a
	.LOBYTES oam_frameset_1b
	.LOBYTES oam_frameset_1c
	.LOBYTES oam_frameset_1d
	.LOBYTES oam_frameset_1e
	.LOBYTES oam_frameset_1f
	.LOBYTES oam_frameset_20
	.LOBYTES oam_frameset_21
	.LOBYTES oam_frameset_22
	.LOBYTES oam_frameset_23
	.LOBYTES oam_frameset_24
	.LOBYTES oam_frameset_25
	.LOBYTES oam_frameset_26
	.LOBYTES oam_frameset_27
	.LOBYTES oam_frameset_28
	.LOBYTES oam_frameset_29
	.LOBYTES oam_frameset_2a
	.LOBYTES oam_frameset_2b
	.LOBYTES oam_frameset_2c
	.LOBYTES oam_frameset_2d
	.LOBYTES oam_frameset_2e
	.LOBYTES oam_frameset_2f
	.LOBYTES oam_frameset_30
	.LOBYTES oam_frameset_31
	.LOBYTES oam_frameset_32
	.LOBYTES oam_frameset_33
	.LOBYTES oam_frameset_34
	.LOBYTES oam_frameset_35
	.LOBYTES oam_frameset_36
	.LOBYTES oam_frameset_37
	.LOBYTES oam_frameset_38
	.LOBYTES oam_frameset_39
	.LOBYTES oam_frameset_3a
	.LOBYTES oam_frameset_3b
	.LOBYTES oam_frameset_3c
	.LOBYTES oam_frameset_3d
	.LOBYTES oam_frameset_3e
	.LOBYTES oam_frameset_3f
	.LOBYTES oam_frameset_40
	.LOBYTES oam_frameset_41
	.LOBYTES oam_frameset_42
	.LOBYTES oam_frameset_43
	.LOBYTES oam_frameset_44
	.LOBYTES oam_frameset_45
	.LOBYTES oam_frameset_46
	.LOBYTES oam_frameset_47
	.LOBYTES oam_frameset_48
	.LOBYTES oam_frameset_49
	.LOBYTES oam_frameset_4a
	.LOBYTES oam_frameset_4b
	.LOBYTES oam_frameset_4c
	.LOBYTES oam_frameset_4d
	.LOBYTES oam_frameset_4e
	.LOBYTES oam_frameset_4f
	.LOBYTES oam_frameset_50
	.LOBYTES oam_frameset_51
	.LOBYTES oam_frameset_52
	.LOBYTES oam_frameset_53
	.LOBYTES oam_frameset_54
	.LOBYTES oam_frameset_55
	.LOBYTES oam_frameset_56
	.LOBYTES oam_frameset_57
	.LOBYTES oam_frameset_58
	.LOBYTES oam_frameset_59
	.LOBYTES oam_frameset_5a
	.LOBYTES oam_frameset_5b
	.LOBYTES oam_frameset_5c
	.LOBYTES oam_frameset_5d
	.LOBYTES oam_frameset_5e
	.LOBYTES oam_frameset_5f
	.LOBYTES oam_frameset_60
	.LOBYTES oam_frameset_61
	.LOBYTES oam_frameset_62
	.LOBYTES oam_frameset_63
	.LOBYTES oam_frameset_64
	.LOBYTES oam_frameset_65
	.LOBYTES oam_frameset_66
	.LOBYTES oam_frameset_67
	.LOBYTES oam_frameset_68
	.LOBYTES oam_frameset_69
	.LOBYTES oam_frameset_6a
	.LOBYTES oam_frameset_6b
	.LOBYTES oam_frameset_6c
	.LOBYTES oam_frameset_6d
	.LOBYTES oam_frameset_6e
	.LOBYTES oam_frameset_6f
	.LOBYTES oam_frameset_70
	.LOBYTES oam_frameset_71
	.LOBYTES oam_frameset_72
	.LOBYTES oam_frameset_73
	.LOBYTES oam_frameset_74
	.LOBYTES oam_frameset_75
	.LOBYTES oam_frameset_76
	.LOBYTES oam_frameset_77
	.LOBYTES oam_frameset_78
	.LOBYTES oam_frameset_79
	.LOBYTES oam_frameset_7a
	.LOBYTES oam_frameset_7b
	.LOBYTES oam_frameset_7c
	.LOBYTES oam_frameset_7d
	.LOBYTES oam_frameset_7e
	.LOBYTES oam_frameset_7f
	.LOBYTES oam_frameset_80
	.LOBYTES oam_frameset_81
	.LOBYTES oam_frameset_82
	.LOBYTES oam_frameset_83
	.LOBYTES oam_frameset_84
	.LOBYTES oam_frameset_85
	.LOBYTES oam_frameset_86
	.LOBYTES oam_frameset_87
	.LOBYTES oam_frameset_88
	.LOBYTES oam_frameset_89
	.LOBYTES oam_frameset_8a
	.LOBYTES oam_frameset_8b
	.LOBYTES oam_frameset_8c
	.LOBYTES oam_frameset_8d
	.LOBYTES oam_frameset_8e
	.LOBYTES oam_frameset_8f
	.LOBYTES oam_frameset_90
	.LOBYTES oam_frameset_91
	.LOBYTES oam_frameset_92
	.LOBYTES oam_frameset_93
	.LOBYTES oam_frameset_94
	.LOBYTES oam_frameset_95
	.LOBYTES oam_frameset_96
	.LOBYTES oam_frameset_97
	.LOBYTES oam_frameset_98
	.LOBYTES oam_frameset_99
	.LOBYTES oam_frameset_9a
	.LOBYTES oam_frameset_9b
	.LOBYTES oam_frameset_9c
	.LOBYTES oam_frameset_9d
	.LOBYTES oam_frameset_9e
	.LOBYTES oam_frameset_9f
	.LOBYTES oam_frameset_a0
	.LOBYTES oam_frameset_a1
	.LOBYTES oam_frameset_a2
	.LOBYTES oam_frameset_a3
	.LOBYTES oam_frameset_a4
	.LOBYTES oam_frameset_a5
	.LOBYTES oam_frameset_a6
	.LOBYTES oam_frameset_a7
	.LOBYTES oam_frameset_a8
	.LOBYTES oam_frameset_a9
	.LOBYTES oam_frameset_aa
	.LOBYTES oam_frameset_ab
	.LOBYTES oam_frameset_ac
	.LOBYTES oam_frameset_ad
	.LOBYTES oam_frameset_ae
	.LOBYTES oam_frameset_af
	.LOBYTES oam_frameset_b0
	.LOBYTES oam_frameset_b1
	.LOBYTES oam_frameset_b2
	.LOBYTES oam_frameset_b3
	.LOBYTES oam_frameset_b4
	.LOBYTES oam_frameset_b5
	.LOBYTES oam_frameset_b6
	.LOBYTES oam_frameset_b7
	.LOBYTES oam_frameset_b8
	.LOBYTES oam_frameset_b9
	.LOBYTES oam_frameset_ba
	.LOBYTES oam_frameset_bb
	.LOBYTES oam_frameset_bc
	.LOBYTES oam_frameset_bd
	.LOBYTES oam_frameset_be
	.LOBYTES oam_frameset_bf
	.LOBYTES oam_frameset_c0
	.LOBYTES oam_frameset_c1
	.LOBYTES oam_frameset_c2
	.LOBYTES oam_frameset_c3
	.LOBYTES oam_frameset_c4
	.LOBYTES oam_frameset_c5
	.LOBYTES oam_frameset_c6
	.LOBYTES oam_frameset_c7
	.LOBYTES oam_frameset_c8
	.LOBYTES oam_frameset_c9
	.LOBYTES oam_frameset_ca
	.LOBYTES oam_frameset_cb
	.LOBYTES oam_frameset_cc
	.LOBYTES oam_frameset_cd
	.LOBYTES oam_frameset_ce
	.LOBYTES oam_frameset_cf

;unused
	.BYTE $FF, $FF, $FF, $FD, $FF, $FF, $FF, $DD
	.BYTE $FF, $FF, $FF, $FF, $FF, $7F, $FF, $7F
	.BYTE $FF, $7F, $FF, $7F, $FF, $F7, $FF, $FF
	.BYTE $DF, $5F, $FF, $FF, $FF, $FF, $FF, $DF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF


oam_frameset_hi_pointers:
	.HIBYTES oam_frameset_00
	.HIBYTES oam_frameset_01
	.HIBYTES oam_frameset_02
	.HIBYTES oam_frameset_03
	.HIBYTES oam_frameset_04
	.HIBYTES oam_frameset_05
	.HIBYTES oam_frameset_06
	.HIBYTES oam_frameset_07
	.HIBYTES oam_frameset_08
	.HIBYTES oam_frameset_09
	.HIBYTES oam_frameset_0a
	.HIBYTES oam_frameset_0b
	.HIBYTES oam_frameset_0c
	.HIBYTES oam_frameset_0d
	.HIBYTES oam_frameset_0e
	.HIBYTES oam_frameset_0f
	.HIBYTES oam_frameset_10
	.HIBYTES oam_frameset_11
	.HIBYTES oam_frameset_12
	.HIBYTES oam_frameset_13
	.HIBYTES oam_frameset_14
	.HIBYTES oam_frameset_15
	.HIBYTES oam_frameset_16
	.HIBYTES oam_frameset_17
	.HIBYTES oam_frameset_18
	.HIBYTES oam_frameset_19
	.HIBYTES oam_frameset_1a
	.HIBYTES oam_frameset_1b
	.HIBYTES oam_frameset_1c
	.HIBYTES oam_frameset_1d
	.HIBYTES oam_frameset_1e
	.HIBYTES oam_frameset_1f
	.HIBYTES oam_frameset_20
	.HIBYTES oam_frameset_21
	.HIBYTES oam_frameset_22
	.HIBYTES oam_frameset_23
	.HIBYTES oam_frameset_24
	.HIBYTES oam_frameset_25
	.HIBYTES oam_frameset_26
	.HIBYTES oam_frameset_27
	.HIBYTES oam_frameset_28
	.HIBYTES oam_frameset_29
	.HIBYTES oam_frameset_2a
	.HIBYTES oam_frameset_2b
	.HIBYTES oam_frameset_2c
	.HIBYTES oam_frameset_2d
	.HIBYTES oam_frameset_2e
	.HIBYTES oam_frameset_2f
	.HIBYTES oam_frameset_30
	.HIBYTES oam_frameset_31
	.HIBYTES oam_frameset_32
	.HIBYTES oam_frameset_33
	.HIBYTES oam_frameset_34
	.HIBYTES oam_frameset_35
	.HIBYTES oam_frameset_36
	.HIBYTES oam_frameset_37
	.HIBYTES oam_frameset_38
	.HIBYTES oam_frameset_39
	.HIBYTES oam_frameset_3a
	.HIBYTES oam_frameset_3b
	.HIBYTES oam_frameset_3c
	.HIBYTES oam_frameset_3d
	.HIBYTES oam_frameset_3e
	.HIBYTES oam_frameset_3f
	.HIBYTES oam_frameset_40
	.HIBYTES oam_frameset_41
	.HIBYTES oam_frameset_42
	.HIBYTES oam_frameset_43
	.HIBYTES oam_frameset_44
	.HIBYTES oam_frameset_45
	.HIBYTES oam_frameset_46
	.HIBYTES oam_frameset_47
	.HIBYTES oam_frameset_48
	.HIBYTES oam_frameset_49
	.HIBYTES oam_frameset_4a
	.HIBYTES oam_frameset_4b
	.HIBYTES oam_frameset_4c
	.HIBYTES oam_frameset_4d
	.HIBYTES oam_frameset_4e
	.HIBYTES oam_frameset_4f
	.HIBYTES oam_frameset_50
	.HIBYTES oam_frameset_51
	.HIBYTES oam_frameset_52
	.HIBYTES oam_frameset_53
	.HIBYTES oam_frameset_54
	.HIBYTES oam_frameset_55
	.HIBYTES oam_frameset_56
	.HIBYTES oam_frameset_57
	.HIBYTES oam_frameset_58
	.HIBYTES oam_frameset_59
	.HIBYTES oam_frameset_5a
	.HIBYTES oam_frameset_5b
	.HIBYTES oam_frameset_5c
	.HIBYTES oam_frameset_5d
	.HIBYTES oam_frameset_5e
	.HIBYTES oam_frameset_5f
	.HIBYTES oam_frameset_60
	.HIBYTES oam_frameset_61
	.HIBYTES oam_frameset_62
	.HIBYTES oam_frameset_63
	.HIBYTES oam_frameset_64
	.HIBYTES oam_frameset_65
	.HIBYTES oam_frameset_66
	.HIBYTES oam_frameset_67
	.HIBYTES oam_frameset_68
	.HIBYTES oam_frameset_69
	.HIBYTES oam_frameset_6a
	.HIBYTES oam_frameset_6b
	.HIBYTES oam_frameset_6c
	.HIBYTES oam_frameset_6d
	.HIBYTES oam_frameset_6e
	.HIBYTES oam_frameset_6f
	.HIBYTES oam_frameset_70
	.HIBYTES oam_frameset_71
	.HIBYTES oam_frameset_72
	.HIBYTES oam_frameset_73
	.HIBYTES oam_frameset_74
	.HIBYTES oam_frameset_75
	.HIBYTES oam_frameset_76
	.HIBYTES oam_frameset_77
	.HIBYTES oam_frameset_78
	.HIBYTES oam_frameset_79
	.HIBYTES oam_frameset_7a
	.HIBYTES oam_frameset_7b
	.HIBYTES oam_frameset_7c
	.HIBYTES oam_frameset_7d
	.HIBYTES oam_frameset_7e
	.HIBYTES oam_frameset_7f
	.HIBYTES oam_frameset_80
	.HIBYTES oam_frameset_81
	.HIBYTES oam_frameset_82
	.HIBYTES oam_frameset_83
	.HIBYTES oam_frameset_84
	.HIBYTES oam_frameset_85
	.HIBYTES oam_frameset_86
	.HIBYTES oam_frameset_87
	.HIBYTES oam_frameset_88
	.HIBYTES oam_frameset_89
	.HIBYTES oam_frameset_8a
	.HIBYTES oam_frameset_8b
	.HIBYTES oam_frameset_8c
	.HIBYTES oam_frameset_8d
	.HIBYTES oam_frameset_8e
	.HIBYTES oam_frameset_8f
	.HIBYTES oam_frameset_90
	.HIBYTES oam_frameset_91
	.HIBYTES oam_frameset_92
	.HIBYTES oam_frameset_93
	.HIBYTES oam_frameset_94
	.HIBYTES oam_frameset_95
	.HIBYTES oam_frameset_96
	.HIBYTES oam_frameset_97
	.HIBYTES oam_frameset_98
	.HIBYTES oam_frameset_99
	.HIBYTES oam_frameset_9a
	.HIBYTES oam_frameset_9b
	.HIBYTES oam_frameset_9c
	.HIBYTES oam_frameset_9d
	.HIBYTES oam_frameset_9e
	.HIBYTES oam_frameset_9f
	.HIBYTES oam_frameset_a0
	.HIBYTES oam_frameset_a1
	.HIBYTES oam_frameset_a2
	.HIBYTES oam_frameset_a3
	.HIBYTES oam_frameset_a4
	.HIBYTES oam_frameset_a5
	.HIBYTES oam_frameset_a6
	.HIBYTES oam_frameset_a7
	.HIBYTES oam_frameset_a8
	.HIBYTES oam_frameset_a9
	.HIBYTES oam_frameset_aa
	.HIBYTES oam_frameset_ab
	.HIBYTES oam_frameset_ac
	.HIBYTES oam_frameset_ad
	.HIBYTES oam_frameset_ae
	.HIBYTES oam_frameset_af
	.HIBYTES oam_frameset_b0
	.HIBYTES oam_frameset_b1
	.HIBYTES oam_frameset_b2
	.HIBYTES oam_frameset_b3
	.HIBYTES oam_frameset_b4
	.HIBYTES oam_frameset_b5
	.HIBYTES oam_frameset_b6
	.HIBYTES oam_frameset_b7
	.HIBYTES oam_frameset_b8
	.HIBYTES oam_frameset_b9
	.HIBYTES oam_frameset_ba
	.HIBYTES oam_frameset_bb
	.HIBYTES oam_frameset_bc
	.HIBYTES oam_frameset_bd
	.HIBYTES oam_frameset_be
	.HIBYTES oam_frameset_bf
	.HIBYTES oam_frameset_c0
	.HIBYTES oam_frameset_c1
	.HIBYTES oam_frameset_c2
	.HIBYTES oam_frameset_c3
	.HIBYTES oam_frameset_c4
	.HIBYTES oam_frameset_c5
	.HIBYTES oam_frameset_c6
	.HIBYTES oam_frameset_c7
	.HIBYTES oam_frameset_c8
	.HIBYTES oam_frameset_c9
	.HIBYTES oam_frameset_ca
	.HIBYTES oam_frameset_cb
	.HIBYTES oam_frameset_cc
	.HIBYTES oam_frameset_cd
	.HIBYTES oam_frameset_ce
	.HIBYTES oam_frameset_cf
