;oamcoord pointers
;lo
	.LOBYTES oamcoord_00
	.LOBYTES oamcoord_01
	.LOBYTES oamcoord_02
	.LOBYTES oamcoord_03
	.LOBYTES oamcoord_04
	.LOBYTES oamcoord_05
	.LOBYTES oamcoord_06
	.LOBYTES oamcoord_07
	.LOBYTES oamcoord_08
	.LOBYTES oamcoord_09
	.LOBYTES oamcoord_0a
	.LOBYTES oamcoord_0b
	.LOBYTES oamcoord_0c
	.LOBYTES oamcoord_0d
	.LOBYTES oamcoord_0e
	.LOBYTES oamcoord_0f
	.LOBYTES oamcoord_10
	.LOBYTES oamcoord_11
	.LOBYTES oamcoord_12
	.LOBYTES oamcoord_13
	.LOBYTES oamcoord_14
	.LOBYTES oamcoord_15
	.LOBYTES oamcoord_16
	.LOBYTES oamcoord_17
	.LOBYTES oamcoord_18
	.LOBYTES oamcoord_19
	.LOBYTES oamcoord_1a
	.LOBYTES oamcoord_1b
	.LOBYTES oamcoord_1c
	.LOBYTES oamcoord_1d
	.LOBYTES oamcoord_1e
	.LOBYTES oamcoord_1f
	.LOBYTES oamcoord_20
	.LOBYTES oamcoord_21
	.LOBYTES oamcoord_22
	.LOBYTES oamcoord_23
	.LOBYTES oamcoord_24
	.LOBYTES oamcoord_25
	.LOBYTES oamcoord_26
	.LOBYTES oamcoord_27
	.LOBYTES oamcoord_28
	.LOBYTES oamcoord_29
	.LOBYTES oamcoord_2a
	.LOBYTES oamcoord_2b
	.LOBYTES oamcoord_2c
	.LOBYTES oamcoord_2d
	.LOBYTES oamcoord_2e
	.LOBYTES oamcoord_2f
	.LOBYTES oamcoord_30
	.LOBYTES oamcoord_31
	.LOBYTES oamcoord_32
	.LOBYTES oamcoord_33
	.LOBYTES oamcoord_34
	.LOBYTES oamcoord_35
	.LOBYTES oamcoord_36
	.LOBYTES oamcoord_37
	.LOBYTES oamcoord_38
	.LOBYTES oamcoord_39
	.LOBYTES oamcoord_3a
	.LOBYTES oamcoord_3b
	.LOBYTES oamcoord_3c
	.LOBYTES oamcoord_3d
	.LOBYTES oamcoord_3e
	.LOBYTES oamcoord_3f
	.LOBYTES oamcoord_40
	.LOBYTES oamcoord_41
	.LOBYTES oamcoord_42
	.LOBYTES oamcoord_43
	.LOBYTES oamcoord_44
	.LOBYTES oamcoord_45
	.LOBYTES oamcoord_46
	.LOBYTES oamcoord_47
	.LOBYTES oamcoord_48
	.LOBYTES oamcoord_49
	.LOBYTES oamcoord_4a
	.LOBYTES oamcoord_4b
	.LOBYTES oamcoord_4c
	.LOBYTES oamcoord_4d
	.LOBYTES oamcoord_4e
	.LOBYTES oamcoord_4f
	.LOBYTES oamcoord_50
	.LOBYTES oamcoord_51
	.LOBYTES oamcoord_52
	.LOBYTES oamcoord_53
	.LOBYTES oamcoord_54
	.LOBYTES oamcoord_55
	.LOBYTES oamcoord_56
	.LOBYTES oamcoord_57
	.LOBYTES oamcoord_58
	.LOBYTES oamcoord_59
	.LOBYTES oamcoord_5a
	.LOBYTES oamcoord_5b
	.LOBYTES oamcoord_5c
	.LOBYTES oamcoord_5d
	.LOBYTES oamcoord_5e
	.LOBYTES oamcoord_5f
	.LOBYTES oamcoord_60
	.LOBYTES oamcoord_61
	.LOBYTES oamcoord_62
	.LOBYTES oamcoord_63
	.LOBYTES oamcoord_64
	.LOBYTES oamcoord_65
	.LOBYTES oamcoord_66
	.LOBYTES oamcoord_67
	.LOBYTES oamcoord_68
	.LOBYTES oamcoord_69
	.LOBYTES oamcoord_6a
	.LOBYTES oamcoord_6b
	.LOBYTES oamcoord_6c
	.LOBYTES oamcoord_6d
	.LOBYTES oamcoord_6e
	.LOBYTES oamcoord_6f
	.LOBYTES oamcoord_70
	.LOBYTES oamcoord_71
	.LOBYTES oamcoord_72
	.LOBYTES oamcoord_73
	.LOBYTES oamcoord_74
	.LOBYTES oamcoord_75
	.LOBYTES oamcoord_76
	.LOBYTES oamcoord_77
	.LOBYTES oamcoord_78
	.LOBYTES oamcoord_79
	.LOBYTES oamcoord_7a
	.LOBYTES oamcoord_7b
	.LOBYTES oamcoord_7c
	.LOBYTES oamcoord_7d
	.LOBYTES oamcoord_7e
	.LOBYTES oamcoord_7f
	.LOBYTES oamcoord_80
	.LOBYTES oamcoord_81
	.LOBYTES oamcoord_82
	.LOBYTES oamcoord_83
	.LOBYTES oamcoord_84
	.LOBYTES oamcoord_85
	.LOBYTES oamcoord_86
	.LOBYTES oamcoord_87
	.LOBYTES oamcoord_88
	.LOBYTES oamcoord_89
	.LOBYTES oamcoord_8a
	.LOBYTES oamcoord_8b
	.LOBYTES oamcoord_8c
	.LOBYTES oamcoord_8d
	.LOBYTES oamcoord_8e
	.LOBYTES oamcoord_8f
	.LOBYTES oamcoord_90
	.LOBYTES oamcoord_91
	.LOBYTES oamcoord_92
	.LOBYTES oamcoord_93
	.LOBYTES oamcoord_94
	.LOBYTES oamcoord_95
	.LOBYTES oamcoord_96
	.LOBYTES oamcoord_97
	.LOBYTES oamcoord_98
	.LOBYTES oamcoord_99
	.LOBYTES oamcoord_9a
	.LOBYTES oamcoord_9b
	.LOBYTES oamcoord_9c
	.LOBYTES oamcoord_9d
	.LOBYTES oamcoord_9e
	.LOBYTES oamcoord_9f
	.LOBYTES oamcoord_a0
	.LOBYTES oamcoord_a1
	.LOBYTES oamcoord_a2
	.LOBYTES oamcoord_a3
	.LOBYTES oamcoord_a4
	.LOBYTES oamcoord_a5
	.LOBYTES oamcoord_a6
	.LOBYTES oamcoord_a7
	.LOBYTES oamcoord_a8
	.LOBYTES oamcoord_a9
	.LOBYTES oamcoord_aa
	.LOBYTES oamcoord_ab
	.LOBYTES oamcoord_ac
	.LOBYTES oamcoord_ad
	.LOBYTES oamcoord_ae
	.LOBYTES oamcoord_af
	.LOBYTES oamcoord_b0
	.LOBYTES oamcoord_b1
	.LOBYTES oamcoord_b2
	.LOBYTES oamcoord_b3
	.LOBYTES oamcoord_b4
	.LOBYTES oamcoord_b5
	.LOBYTES oamcoord_b6
	.LOBYTES oamcoord_b7
	.LOBYTES oamcoord_b8
	.LOBYTES oamcoord_b9
	.LOBYTES oamcoord_ba
	.LOBYTES oamcoord_bb
	.LOBYTES oamcoord_bc
	.LOBYTES oamcoord_bd
	.LOBYTES oamcoord_be
	.LOBYTES oamcoord_bf
	.LOBYTES oamcoord_c0
	.LOBYTES oamcoord_c1
	.LOBYTES oamcoord_c2
	.LOBYTES oamcoord_c3
	.LOBYTES oamcoord_c4
	.LOBYTES oamcoord_c5
	.LOBYTES oamcoord_c6
	.LOBYTES oamcoord_c7
	.LOBYTES oamcoord_c8
	.LOBYTES oamcoord_c9
	.LOBYTES oamcoord_ca
	.LOBYTES oamcoord_cb
	.LOBYTES oamcoord_cc
	.LOBYTES oamcoord_cd
	.LOBYTES oamcoord_ce
	.LOBYTES oamcoord_cf
	.LOBYTES oamcoord_d0
	.LOBYTES oamcoord_d1
	.LOBYTES oamcoord_d2
	.LOBYTES oamcoord_d3
	.LOBYTES oamcoord_d4
	.LOBYTES oamcoord_d5
	.LOBYTES oamcoord_d6
	.LOBYTES oamcoord_d7
	.LOBYTES oamcoord_d8
	.LOBYTES oamcoord_d9
	.LOBYTES oamcoord_da
	.LOBYTES oamcoord_db
	.LOBYTES oamcoord_dc
	.LOBYTES oamcoord_dd
	.LOBYTES oamcoord_de
	.LOBYTES oamcoord_df
	.LOBYTES oamcoord_e0
	.LOBYTES oamcoord_e1
	.LOBYTES oamcoord_e2
	.LOBYTES oamcoord_e3
	.LOBYTES oamcoord_e4
	.LOBYTES oamcoord_e5
	.LOBYTES oamcoord_e6
	.LOBYTES oamcoord_e7
	.LOBYTES oamcoord_e8
	.LOBYTES oamcoord_e9
	.LOBYTES oamcoord_ea
	.LOBYTES oamcoord_eb
	.LOBYTES oamcoord_ec
	.LOBYTES oamcoord_ed
	.LOBYTES oamcoord_ee
	.LOBYTES oamcoord_ef

;unused
	.BYTE $FF, $FD, $FF, $7F, $FF, $FF, $FF, $7F
	.BYTE $FF, $FF, $FF, $FD, $FF, $5F, $FF, $FF

;hi
	.HIBYTES oamcoord_00
	.HIBYTES oamcoord_01
	.HIBYTES oamcoord_02
	.HIBYTES oamcoord_03
	.HIBYTES oamcoord_04
	.HIBYTES oamcoord_05
	.HIBYTES oamcoord_06
	.HIBYTES oamcoord_07
	.HIBYTES oamcoord_08
	.HIBYTES oamcoord_09
	.HIBYTES oamcoord_0a
	.HIBYTES oamcoord_0b
	.HIBYTES oamcoord_0c
	.HIBYTES oamcoord_0d
	.HIBYTES oamcoord_0e
	.HIBYTES oamcoord_0f
	.HIBYTES oamcoord_10
	.HIBYTES oamcoord_11
	.HIBYTES oamcoord_12
	.HIBYTES oamcoord_13
	.HIBYTES oamcoord_14
	.HIBYTES oamcoord_15
	.HIBYTES oamcoord_16
	.HIBYTES oamcoord_17
	.HIBYTES oamcoord_18
	.HIBYTES oamcoord_19
	.HIBYTES oamcoord_1a
	.HIBYTES oamcoord_1b
	.HIBYTES oamcoord_1c
	.HIBYTES oamcoord_1d
	.HIBYTES oamcoord_1e
	.HIBYTES oamcoord_1f
	.HIBYTES oamcoord_20
	.HIBYTES oamcoord_21
	.HIBYTES oamcoord_22
	.HIBYTES oamcoord_23
	.HIBYTES oamcoord_24
	.HIBYTES oamcoord_25
	.HIBYTES oamcoord_26
	.HIBYTES oamcoord_27
	.HIBYTES oamcoord_28
	.HIBYTES oamcoord_29
	.HIBYTES oamcoord_2a
	.HIBYTES oamcoord_2b
	.HIBYTES oamcoord_2c
	.HIBYTES oamcoord_2d
	.HIBYTES oamcoord_2e
	.HIBYTES oamcoord_2f
	.HIBYTES oamcoord_30
	.HIBYTES oamcoord_31
	.HIBYTES oamcoord_32
	.HIBYTES oamcoord_33
	.HIBYTES oamcoord_34
	.HIBYTES oamcoord_35
	.HIBYTES oamcoord_36
	.HIBYTES oamcoord_37
	.HIBYTES oamcoord_38
	.HIBYTES oamcoord_39
	.HIBYTES oamcoord_3a
	.HIBYTES oamcoord_3b
	.HIBYTES oamcoord_3c
	.HIBYTES oamcoord_3d
	.HIBYTES oamcoord_3e
	.HIBYTES oamcoord_3f
	.HIBYTES oamcoord_40
	.HIBYTES oamcoord_41
	.HIBYTES oamcoord_42
	.HIBYTES oamcoord_43
	.HIBYTES oamcoord_44
	.HIBYTES oamcoord_45
	.HIBYTES oamcoord_46
	.HIBYTES oamcoord_47
	.HIBYTES oamcoord_48
	.HIBYTES oamcoord_49
	.HIBYTES oamcoord_4a
	.HIBYTES oamcoord_4b
	.HIBYTES oamcoord_4c
	.HIBYTES oamcoord_4d
	.HIBYTES oamcoord_4e
	.HIBYTES oamcoord_4f
	.HIBYTES oamcoord_50
	.HIBYTES oamcoord_51
	.HIBYTES oamcoord_52
	.HIBYTES oamcoord_53
	.HIBYTES oamcoord_54
	.HIBYTES oamcoord_55
	.HIBYTES oamcoord_56
	.HIBYTES oamcoord_57
	.HIBYTES oamcoord_58
	.HIBYTES oamcoord_59
	.HIBYTES oamcoord_5a
	.HIBYTES oamcoord_5b
	.HIBYTES oamcoord_5c
	.HIBYTES oamcoord_5d
	.HIBYTES oamcoord_5e
	.HIBYTES oamcoord_5f
	.HIBYTES oamcoord_60
	.HIBYTES oamcoord_61
	.HIBYTES oamcoord_62
	.HIBYTES oamcoord_63
	.HIBYTES oamcoord_64
	.HIBYTES oamcoord_65
	.HIBYTES oamcoord_66
	.HIBYTES oamcoord_67
	.HIBYTES oamcoord_68
	.HIBYTES oamcoord_69
	.HIBYTES oamcoord_6a
	.HIBYTES oamcoord_6b
	.HIBYTES oamcoord_6c
	.HIBYTES oamcoord_6d
	.HIBYTES oamcoord_6e
	.HIBYTES oamcoord_6f
	.HIBYTES oamcoord_70
	.HIBYTES oamcoord_71
	.HIBYTES oamcoord_72
	.HIBYTES oamcoord_73
	.HIBYTES oamcoord_74
	.HIBYTES oamcoord_75
	.HIBYTES oamcoord_76
	.HIBYTES oamcoord_77
	.HIBYTES oamcoord_78
	.HIBYTES oamcoord_79
	.HIBYTES oamcoord_7a
	.HIBYTES oamcoord_7b
	.HIBYTES oamcoord_7c
	.HIBYTES oamcoord_7d
	.HIBYTES oamcoord_7e
	.HIBYTES oamcoord_7f
	.HIBYTES oamcoord_80
	.HIBYTES oamcoord_81
	.HIBYTES oamcoord_82
	.HIBYTES oamcoord_83
	.HIBYTES oamcoord_84
	.HIBYTES oamcoord_85
	.HIBYTES oamcoord_86
	.HIBYTES oamcoord_87
	.HIBYTES oamcoord_88
	.HIBYTES oamcoord_89
	.HIBYTES oamcoord_8a
	.HIBYTES oamcoord_8b
	.HIBYTES oamcoord_8c
	.HIBYTES oamcoord_8d
	.HIBYTES oamcoord_8e
	.HIBYTES oamcoord_8f
	.HIBYTES oamcoord_90
	.HIBYTES oamcoord_91
	.HIBYTES oamcoord_92
	.HIBYTES oamcoord_93
	.HIBYTES oamcoord_94
	.HIBYTES oamcoord_95
	.HIBYTES oamcoord_96
	.HIBYTES oamcoord_97
	.HIBYTES oamcoord_98
	.HIBYTES oamcoord_99
	.HIBYTES oamcoord_9a
	.HIBYTES oamcoord_9b
	.HIBYTES oamcoord_9c
	.HIBYTES oamcoord_9d
	.HIBYTES oamcoord_9e
	.HIBYTES oamcoord_9f
	.HIBYTES oamcoord_a0
	.HIBYTES oamcoord_a1
	.HIBYTES oamcoord_a2
	.HIBYTES oamcoord_a3
	.HIBYTES oamcoord_a4
	.HIBYTES oamcoord_a5
	.HIBYTES oamcoord_a6
	.HIBYTES oamcoord_a7
	.HIBYTES oamcoord_a8
	.HIBYTES oamcoord_a9
	.HIBYTES oamcoord_aa
	.HIBYTES oamcoord_ab
	.HIBYTES oamcoord_ac
	.HIBYTES oamcoord_ad
	.HIBYTES oamcoord_ae
	.HIBYTES oamcoord_af
	.HIBYTES oamcoord_b0
	.HIBYTES oamcoord_b1
	.HIBYTES oamcoord_b2
	.HIBYTES oamcoord_b3
	.HIBYTES oamcoord_b4
	.HIBYTES oamcoord_b5
	.HIBYTES oamcoord_b6
	.HIBYTES oamcoord_b7
	.HIBYTES oamcoord_b8
	.HIBYTES oamcoord_b9
	.HIBYTES oamcoord_ba
	.HIBYTES oamcoord_bb
	.HIBYTES oamcoord_bc
	.HIBYTES oamcoord_bd
	.HIBYTES oamcoord_be
	.HIBYTES oamcoord_bf
	.HIBYTES oamcoord_c0
	.HIBYTES oamcoord_c1
	.HIBYTES oamcoord_c2
	.HIBYTES oamcoord_c3
	.HIBYTES oamcoord_c4
	.HIBYTES oamcoord_c5
	.HIBYTES oamcoord_c6
	.HIBYTES oamcoord_c7
	.HIBYTES oamcoord_c8
	.HIBYTES oamcoord_c9
	.HIBYTES oamcoord_ca
	.HIBYTES oamcoord_cb
	.HIBYTES oamcoord_cc
	.HIBYTES oamcoord_cd
	.HIBYTES oamcoord_ce
	.HIBYTES oamcoord_cf
	.HIBYTES oamcoord_d0
	.HIBYTES oamcoord_d1
	.HIBYTES oamcoord_d2
	.HIBYTES oamcoord_d3
	.HIBYTES oamcoord_d4
	.HIBYTES oamcoord_d5
	.HIBYTES oamcoord_d6
	.HIBYTES oamcoord_d7
	.HIBYTES oamcoord_d8
	.HIBYTES oamcoord_d9
	.HIBYTES oamcoord_da
	.HIBYTES oamcoord_db
	.HIBYTES oamcoord_dc
	.HIBYTES oamcoord_dd
	.HIBYTES oamcoord_de
	.HIBYTES oamcoord_df
	.HIBYTES oamcoord_e0
	.HIBYTES oamcoord_e1
	.HIBYTES oamcoord_e2
	.HIBYTES oamcoord_e3
	.HIBYTES oamcoord_e4
	.HIBYTES oamcoord_e5
	.HIBYTES oamcoord_e6
	.HIBYTES oamcoord_e7
	.HIBYTES oamcoord_e8
	.HIBYTES oamcoord_e9
	.HIBYTES oamcoord_ea
	.HIBYTES oamcoord_eb
	.HIBYTES oamcoord_ec
	.HIBYTES oamcoord_ed
	.HIBYTES oamcoord_ee
	.HIBYTES oamcoord_ef

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $DF, $FF, $FF, $FF, $FD
